<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: rudanok
 * Date: Wed, 05 Jun 2013 09:42:17 +0400
 */

$conf['title'] = '1С:Регистрация';
$conf['lang'] = 'ru';
$conf['tagline'] = 'Руководство пользователя';
$conf['license'] = '';
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'recent,register';
$conf['htmlok'] = 1;
$conf['subscribers'] = 1;
$conf['mailprefix'] = 'Reg';
$conf['userewrite'] = '1';

// end auto-generated content
